// USER REDUCER ACTIONS
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const UPDATE_USER = 'UPDATE_USER';

// SETTINGS REDUCER ACTIONS
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const SET_STATUS_MESSAGE = 'SET_STATUS_MESSAGE';
export const SET_LOADING = 'SET_LOADING';

// MODAL REDUCER ACTIONS
export const SET_MODAL = 'SET_MODAL';

// ORGANIZATION REDUCER ACTIONS
export const SET_ORGANIZATION = 'SET_ORGANIZATION';
export const CLEAR_ORGANIZATION = 'CLEAR_ORGANIZATION';
